spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: schedule-service
          uri: http://schedule-service:8081
          predicates:
            - Path=/api/schedule-service/**

