version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-keycloack
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: keycloak_db
    ports:
      - 3306:3306
    volumes:
      - mysql_keycloak_data:/var/lib/mysql

  kc:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloack
    environment:
      DB_VENDOR: mysql
      DB_ADDR: db
      DB_DATABASE: keycloak_db
      DB_USER: admin
      DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KEYCLOAK_HOSTNAME: kc
    ports:
      - 9090:8080
    depends_on:
      - db
    command:
      - start-dev

  gateway-service:
    image: gateway-service:latest
    container_name: gateway-service
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kc

################## SCHEDULE MICROSERVICE ##################
  db-schedule:
    image: mysql:8.0
    container_name: mysql-schedule
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: schedule_db
    ports:
      - 3307:3306
    volumes:
      - mysql_schedule_data:/var/lib/mysql
    profiles:
      - schedule-service

  schedule-service:
    image: schedule-service:latest
    container_name: schedule-service
    restart: always
    depends_on:
      - db-schedule
      - kc
    ports:
      - 8081:8081
    profiles:
      - schedule-service

################## SCHEDULE MICROSERVICE ##################

volumes:
  mysql_keycloak_data:
  mysql_schedule_data: