version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_USER: my_admin
      MYSQL_PASSWORD: my_password
      MYSQL_DATABASE: keycloak_db
    ports:
      - 3306:3306

  kc:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: mysql
      DB_ADDR: db
      DB_DATABASE: keycloak_db
      DB_USER: my_admin
      DB_PASSWORD: my_password
      KEYCLOAK_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    ports:
      - 9090:8080
    depends_on:
      - db
    command:
      - start-dev